// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKZtIPZhOzP7B0s6wzll88s168MrimQI',
    appId: '1:210507737876:web:1c2ec4d3be71e8d360f001',
    messagingSenderId: '210507737876',
    projectId: 'teeeeee-a2bda',
    authDomain: 'teeeeee-a2bda.firebaseapp.com',
    storageBucket: 'teeeeee-a2bda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy1s0uXpWIClLJuiP5mZNUdfByBcC8_oA',
    appId: '1:210507737876:android:1c797fc6baf1094b60f001',
    messagingSenderId: '210507737876',
    projectId: 'teeeeee-a2bda',
    storageBucket: 'teeeeee-a2bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87bzbdzKqsAuplYjK4mFQAOoT9tcoJP4',
    appId: '1:210507737876:ios:91202b3b14c81cbb60f001',
    messagingSenderId: '210507737876',
    projectId: 'teeeeee-a2bda',
    storageBucket: 'teeeeee-a2bda.appspot.com',
    iosBundleId: 'com.example.deliveryFoodV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87bzbdzKqsAuplYjK4mFQAOoT9tcoJP4',
    appId: '1:210507737876:ios:5594929cff6ac9ef60f001',
    messagingSenderId: '210507737876',
    projectId: 'teeeeee-a2bda',
    storageBucket: 'teeeeee-a2bda.appspot.com',
    iosBundleId: 'com.example.deliveryFoodV1.RunnerTests',
  );
}
